### ISSUE TITLE
Issue with SimG4SaveTrackerHits

### ISSUE THREAD

**Issue by aciarma** [HEP-FCC/k4SimGeant4#43]
Hi, I've noticed that the code crashes while running k4run and trying to save TrackerHits.

The crash occurred within the function SimG4SaveTrackerHits::saveOutput(G4Event const&) in the shared library libSimG4Components.so.

This appeared to work fine until Friday 21/07, but on monday it didn't.
I tried sourcing key4hep-spack of friday or even previous days but it fails.

Is this something known? I don't quite understand also why if I source some older spack versions it does not work...

I attach a test file, using a geometry already on the repo.
Just source whatever key4hep version and `k4run randomtest.py`

[Archivio.zip](https://github.com/HEP-FCC/k4SimGeant4/files/12171003/Archivio.zip)

**Comment by kjvbrt** [comment]
Hi @aciarma,

this issue seems like related to the switch to use frame base I/O in Podio.
I can investigate the issue further next week.

Best,
Juraj

**Comment by kjvbrt** [comment]
Try locally merging this PR: https://github.com/HEP-FCC/k4SimGeant4/pull/40

**Comment by aciarma** [comment]
Hi @kjvbrt, this seems to work sourcing the Jul19 key4hep nightlies before compiling

**Comment by kjvbrt** [comment]
Hi @aciarma, once https://github.com/key4hep/k4FWCore/pull/138 is merged you should be able to use frame data service from the latest nightlies.
