### ISSUE TITLE
New tag

### ISSUE THREAD

**Issue by jmcarcell** [HEP-FCC/k4SimGeant4#48]
The latest tag is from October 2022 and doesn't include fixes like:
https://github.com/HEP-FCC/k4SimGeant4/pull/25 or https://github.com/HEP-FCC/k4SimGeant4/pull/35
The key4hep releases (not the nightlies) pick up the latest tag so the problems that are solved there would still appear. I suggest making a new tag whenever other people want; I don't need it now.

**Comment by andresailer** [comment]
At the latest after #47

**Comment by BrieucF** [comment]
Are you about to release a stable stack? If yes, there are other repositories that we would like to tag first.

**Comment by jmcarcell** [comment]
Not right now, this is a reminder since for this package in particular several things would fail

**Comment by kjvbrt** [comment]
Releasing
