### ISSUE TITLE
SimG4SaveTrackerHits only works with `readoutNames`

### ISSUE THREAD

**Issue by BrieucF** [HEP-FCC/k4SimGeant4#50]
This works:
```
from Configurables import SimG4SaveTrackerHits
savetrackertool = SimG4SaveTrackerHits("SimG4SaveTrackerHits", readoutNames=["CDCHHits"])
```

This does not work: 
```
from Configurables import SimG4SaveTrackerHits
savetrackertool = SimG4SaveTrackerHits("SimG4SaveTrackerHits", readoutNames="CDCHHits")
```

To reproduce you can follow the recipe [here](https://github.com/BrieucF/k4RecTracker#installation) and run 
`k4run DCHdigi/test/runDCHsimpleDigitizerExtendedEdm.py`

**Comment by kjvbrt** [comment]
Hi @BrieucF, but this can't work. The `readoutNames` is of type array (std::vector) of strings.

This should work:
```
from Configurables import SimG4SaveTrackerHits
savetrackertool = SimG4SaveTrackerHits("SimG4SaveTrackerHits", readoutName="CDCHHits")
```

**Comment by BrieucF** [comment]
Sorry, I meant `readoutName="CDCHHits"`. And I should also precise that it runs but produces empty output, sorry I was in a rush when reporting this issue. Tagging @armin-ilg on this as well.
